[phases.setup]
nixPkgs = ["php81", "php81Packages.composer"]

[phases.build]
cmds = ["composer install --no-dev", "php artisan config:cache", "php artisan route:cache"]

[start]
cmd = "php artisan migrate --force && php artisan serve --host=0.0.0.0 --port=$PORT"
